name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 2️⃣ Configure Git
      - name: Configure Git
        run: |
          git config user.name "Nuno Gago"
          git config user.email "nuno.gago@fanduel.com"


      # 3️⃣ Fetch and pull docs from project-a
      - name: Update docs from project-a
        env:
          PAT: ${{ secrets.GH_DOCS_TOKEN }}
        run: |
          REMOTE_NAME="project-a"
          PREFIX="docs/project-a"
          BRANCH="docs-only"
          git remote add $REMOTE_NAME https://x-access-token:${PAT}@github.com/nunorgago/project-a.git || true
          git fetch $REMOTE_NAME

          # check if subtree exists
          if git log -1 --oneline $PREFIX >/dev/null 2>&1; then
            echo "Subtree exists, pulling updates..."
            git subtree pull --prefix=$PREFIX $REMOTE_NAME $BRANCH --squash
          else
            echo "Subtree missing, adding..."
            git subtree add --prefix=$PREFIX $REMOTE_NAME $BRANCH --squash
          fi

      # 4️⃣ Fetch and pull docs from project-b
      - name: Update docs from project-b
        env:
          PAT: ${{ secrets.GH_DOCS_TOKEN }}
        run: |
          REMOTE_NAME="project-b"
          PREFIX="docs/project-b"
          BRANCH="docs-only"
          git remote add $REMOTE_NAME https://x-access-token:${PAT}@github.com/nunorgago/project-b.git || true
          git fetch $REMOTE_NAME

          if git log -1 --oneline $PREFIX >/dev/null 2>&1; then
            echo "Subtree exists, pulling updates..."
            git subtree pull --prefix=$PREFIX $REMOTE_NAME $BRANCH --squash
          else
            echo "Subtree missing, adding..."
            git subtree add --prefix=$PREFIX $REMOTE_NAME $BRANCH --squash
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.4.0'

      - name: Install dependencies
        run: npm ci

      - name: Build Documentation
        run: npm run docs:build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_DOCS_TOKEN }}
          publish_dir: ./build